<!DOCTYPE html>
<html>
<head>
	<title><?=$title?></title>
	<meta charset="UTF-8">
	<meta name="viewport" content="width=device-width,initial-scale=1">
	<link href="https://res.wx.qq.com/open/libs/weui/1.1.3/weui.min.css" rel="stylesheet">
</head>
<body>
	<div class="weui-msg">
		<div class="weui-msg__icon-area">
		<?php
		switch ($type) {
			case 'wait':
				echo '<i class="weui-icon-waiting weui-icon_msg"></i>';
				break;
			case 'success':
				echo '<i class="weui-icon-success weui-icon_msg"></i>';
				break;
			case 'info':
				echo '<i class="weui-icon-info weui-icon_msg"></i>';
				break;
			case 'warn':
				echo '<i class="weui-icon-warn weui-icon_msg"></i>';
				break;
		}
		?>
		</div>
		<div class="weui-msg__text-area">
			<h2 class="weui-msg__title"><?=$message?></h2>
			<p class="weui-msg__desc"><?=$desc?></a></p>
		</div>
		<div class="weui-msg__opr-area">
			<p class="weui-btn-area">
				<a id="continue" href="<?=$url?>" class="weui-btn weui-btn_primary">如果页面没有自动跳转，请点我继续</a>
			</p>
		</div>
		<div class="weui-msg__extra-area">
			<div class="weui-footer">
				<p class="weui-footer__text">Copyright © 2018 微光网络工作室</p>
			</div>
		</div>
	</div>
	<script><?=$extra_script?></script>
	<?php if (!empty($url)) { ?>
	<script>
	setTimeout(() => {
		window.location.href = '<?=$url?>';
	}, <?=$time?>);
	</script>
	<?php } ?>
</body>
</html>