<?php
use yesf\Yesf;
?>
<!DOCTYPE html>
<html>
<head>
	<title>设置</title>
	<meta charset="UTF-8">
	<meta name="viewport" content="width=device-width,initial-scale=1,user-scalable=no">
	<meta http-equiv="X-UA-Compatible" content="IE=edge"/>
	<link href="https://res.wx.qq.com/open/libs/weui/1.1.3/weui.min.css" rel="stylesheet">
</head>
<body>
	<div class="weui-cells__title">基本设置</div>
	<div class="weui-cells weui-cells_form">
		<div class="weui-cell weui-cell_switch">
			<div class="weui-cell__bd">接收消息推送</div>
			<div class="weui-cell__ft">
				<input id="setting-push" class="weui-switch" type="checkbox">
			</div>
		</div>
	</div>
	<div class="weui-btn-area">
        <button id="setting-save" class="weui-btn weui-btn_primary">保存</button>
    </div>
	<script>var BASE_URI='<?=Yesf::getBaseUri()?>';</script>
	<script src="https://res.wx.qq.com/open/libs/weuijs/1.1.4/weui.min.js"></script>
	<script src="<?=$__PUBLIC_URL?>public.js"></script>
</body>
</html>